services:
    CleverAge\ProcessBundle\Command\:
        resource: '../../../Command/*'
        autowire: true
        autoconfigure: true
        bind:
            $eventDispatcher: '@Symfony\Contracts\EventDispatcher\EventDispatcherInterface'
            $container: '@service_container'
