services:
    CleverAge\ProcessBundle\Manager\ProcessManager:
        autowire: true
        public: false
        arguments:
            $eventDispatcher: '@Symfony\Contracts\EventDispatcher\EventDispatcherInterface'
            $container: '@service_container'

    CleverAge\ProcessBundle\Context\ContextualOptionResolver:
        public: false
