services:
    CleverAge\ProcessBundle\Command\:
        resource: '../../../Command/*'
        autowire: true
        autoconfigure: true
        bind:
            $eventDispatcher: '@CleverAge\ProcessBundle\EventDispatcher\BackcompatEventDispatcher'
            $container: '@service_container'
