services:
    CleverAge\ProcessBundle\Manager\ProcessManager:
        autowire: true
        public: false
        arguments:
            $eventDispatcher: '@CleverAge\ProcessBundle\EventDispatcher\BackcompatEventDispatcher'
            $container: '@service_container'

    CleverAge\ProcessBundle\Context\ContextualOptionResolver:
        public: false
